export declare const horizontalImg: string
export declare const hoverImgContainer: string
export declare const howtotakepicturesContent: string
export declare const howtotakepicturesIntro: string
export declare const howtotakepicturesIntro2: string
export declare const inage2306: string
export declare const kozushima2307: string
export declare const personalityContent: string
export declare const personalityIntro: string
export declare const pointImgBad: string
export declare const pointImgContainer: string
export declare const pointImgContent: string
export declare const pointImgGood: string
export declare const pointImgInner: string
export declare const pointSituation: string
export declare const pointTips: string
export declare const sasameTableBottom: string
export declare const sasameTableHead: string
export declare const situationImgContainer: string
export declare const slickSlide: string
export declare const slider: string
export declare const threeTips: string
export declare const threeTipsHeader: string
export declare const tripContent: string
export declare const tripContentInner: string
export declare const tripHeader: string
export declare const tripHeaderBottom: string
export declare const tripHeaderTextMain: string
export declare const tripHeaderTextSub: string
export declare const tripHeaderTop: string
export declare const tripMain: string
export declare const tripMainImgContainer: string
