export declare const allCodeListContainer: string
export declare const appendix: string
export declare const areacodeBody: string
export declare const codeList: string
export declare const codeListBlue: string
export declare const codeListContainer: string
export declare const codeListGreen: string
export declare const codeListNone: string
export declare const codeListRed: string
export declare const codeListYellow: string
export declare const copyrightContainer: string
export declare const headerContainer: string
export declare const headerContent: string
export declare const headerLeft: string
export declare const linkQuiz: string
export declare const linkRandom: string
export declare const linkTitle: string
export declare const maAreaCodeContainer: string
export declare const mainContent: string
export declare const prefAllList: string
export declare const prefAllListContainer: string
export declare const searchBox: string
export declare const searchCityContainer: string
export declare const searchCityContent: string
export declare const searchCityHeader: string
export declare const searchCityList: string
export declare const searchCityTextContainer: string
export declare const searchCityTextOuter: string
export declare const searchPushNumberContent: string
export declare const searchPushNumberExecContainer: string
export declare const searchPushNumberMatchButton: string
export declare const searchPushNumberPrefixButton: string
export declare const searchPushNumberTextContainer: string
