export declare const additionalInfo: string
export declare const areacode: string
export declare const areacodeBody: string
export declare const areacodeNumberband: string
export declare const checkBtnContainer: string
export declare const citiesContainer: string
export declare const citiesContainerOuter: string
export declare const citiesContainerTd: string
export declare const city: string
export declare const cityList: string
export declare const cityListwithBorder: string
export declare const codeListMiddle: string
export declare const countyList: string
export declare const countyName: string
export declare const headerContainer: string
export declare const infoBlock: string
export declare const infoBlockContainer: string
export declare const infoDojinshi: string
export declare const infoRow: string
export declare const infoTable: string
export declare const infoTableContainer: string
export declare const ma: string
export declare const maAreaCodeContainer: string
export declare const maAreaCodeHeader: string
export declare const maCompBlue: string
export declare const maCompGreen: string
export declare const maCompRed: string
export declare const maCompYellow: string
export declare const maInfo: string
export declare const mainHeader: string
export declare const mainHeaderLink: string
export declare const mainHeaderMain: string
export declare const mainHeaderRuby: string
export declare const mainHeaderSub: string
export declare const maNumberBands: string
export declare const maNumberBandsInner: string
export declare const mApref: string
export declare const numberBands: string
export declare const openSearchDetail: string
export declare const openSearchDetailContainer: string
export declare const pref: string
export declare const prefList: string
export declare const prefListSimple: string
export declare const prefofCities: string
export declare const searchBox: string
export declare const subHeader: string
export declare const words: string
