export const rememberWordData = [
  {
    length: '3',
    areacode: '011',
    city: '札幌',
    word: 'いい恋人は札幌市',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '011x',
    city: '札幌',
    word: 'さっさと別れてきた広島',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '012',
    city: '千歳',
    word: 'いつ食べるもの？千歳飴',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0123',
    city: '千歳',
    word: '1・2・3で飛び立て！新千歳空港',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0124',
    city: '芦別',
    word: '西別芦別',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0125',
    city: '滝川',
    word: 'ニコニコタッキーカワイイネ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0126',
    city: '岩見沢',
    word: '岩風呂岩見沢',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '013',
    city: '函館',
    word: '函館の遺産は縄文遺跡群',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0133',
    city: '石狩',
    word: 'さざれ石借りてくよ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0134',
    city: '小樽',
    word: '刺身の小樽',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0135',
    city: '余市',
    word: 'いざこざ起こるよ余り1',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0136',
    city: 'ニセコ',
    word: 'さむいニセコのスキー場',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0137',
    city: '森',
    word: 'みんなの森',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0138',
    city: '函館',
    word: '世界遺産はまだだよ五稜郭',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0139',
    city: '松前',
    word: 'サンキューを待つ前に',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '014',
    city: '室蘭',
    word: '美味しい～！室蘭カレーラーメン',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0142',
    city: '伊達',
    word: '異質な伊達者',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0143',
    city: '室蘭',
    word: 'カレーラーメンの美味しさ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0144',
    city: '苫小牧',
    word: '獅子舞苫小牧',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0145',
    city: '日高',
    word: '横に日高昆布',
    dateAisu: '11/26',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0146',
    city: '浦河',
    word: '白い襟の裏側は',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '015',
    city: '網走',
    word: '試されに行こう道東へ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0152',
    city: '網走',
    word: 'ゴツい刑務所網走監獄',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0153',
    city: '根室',
    word: '根菜根室',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0154',
    city: '釧路',
    word: 'こしろくしろ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0155',
    city: '帯広',
    word: 'ゴーゴー帯広ばんえい競馬',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0156',
    city: '本別',
    word: 'コロコロ本(コミック)別冊',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0157',
    city: '北見',
    word: '小麦の粉は北見産',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0158',
    city: '紋別',
    word: 'ゴーヤの紋章',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '016',
    city: '稚内',
    word: 'いろいろわっかんない',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0162',
    city: '稚内',
    word: '唯一無二もわっかんない',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0163',
    city: '天塩',
    word: '霧散無塩',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0164',
    city: '留萌',
    word: '虫に萌え',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0165',
    city: '名寄',
    word: 'なよろこび',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0166',
    city: '旭川',
    word: 'ろくろ首みたいキリンさん',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0167',
    city: '富良野',
    word: 'いろんな種類のラベンダー',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '017',
    city: '青森',
    word: 'りんご青いな青森県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0172',
    city: '弘前',
    word: '夏前',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0173',
    city: '五所川原',
    word: '波に乗れ揚げたい焼き',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0174',
    city: '今別',
    word: '梨と今別れよう',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0175',
    city: 'むつ',
    word: 'なごむつ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0176',
    city: '十和田',
    word: '南無は永遠だ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0177',
    city: '青森',
    word: '旧暦の7月7日はねぶた祭',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0178',
    city: '八戸',
    word: '八戸',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0179',
    city: '三戸',
    word: '泣くほどうまいニンニクサンド',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '018',
    city: '秋田',
    word: '18歳の秋田美人',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0182',
    city: '横手',
    word: 'パンツ横縞',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0183',
    city: '湯沢',
    word: '婆さんの湯',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0184',
    city: '由利本荘',
    word: 'いやよユリに過保護',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0185',
    city: '男鹿',
    word: '箱入りナマハゲ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0186',
    city: '大館',
    word: 'ハムもおだてりゃ木に登る',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0187',
    city: '仙北',
    word: '戦国の華、大戦',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0188',
    city: '秋田',
    word: 'はっぱの秋だ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '019',
    city: '岩手',
    word: '岩で行くで！',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0191',
    city: '一関',
    word: '一関',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0192',
    city: '大船渡',
    word: '国々を渡る大船',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0193',
    city: '釜石',
    word: '草の釜揚げ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0194',
    city: '久慈',
    word: '久慈',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0195',
    city: '二戸',
    word: '救護だニトログリセリン',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0196',
    city: '盛岡',
    word: '黒い盛岡',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0197',
    city: '北上',
    word: '苦難の北上',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0198',
    city: '花巻',
    word: 'くっぱまき',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '022',
    city: '宮城',
    word: '鬼ずんだもちの宮城県',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0220',
    city: '登米',
    word: '二重に留め具で挟む',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0222',
    city: '仙台',
    word: 'ずずずんだ',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0223',
    city: '岩沼',
    word: '兄さん何も言わぬま',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0224',
    city: '白石',
    word: '白石',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0225',
    city: '石巻',
    word: 'ニコイチの巻',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0226',
    city: '気仙沼',
    word: '風呂の換気扇',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0227',
    city: '仙台',
    word: '通なずんだ',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0228',
    city: '栗原',
    word: 'つやつやの栗だって',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0229',
    city: '大崎',
    word: '古い肉の多さ',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '023',
    city: '山形',
    word: '鬼さくらんぼの山形県',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0233',
    city: '新庄',
    word: '新庄三球三振じょう',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0234',
    city: '酒田',
    word: '刺身とお酒',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0235',
    city: '鶴岡',
    word: '亀から見たら 鶴はザコ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0236',
    city: '山形',
    word: '兄さん向こうの山が回転',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0237',
    city: '村山',
    word: 'みんなの村',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0238',
    city: '米沢',
    word: '米沢牛さんぽ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '024',
    city: '福島',
    word: 'ふーしま県',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0240',
    city: '大熊',
    word: '夜空のおおぐま座',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0241',
    city: '喜多方',
    word: 'お寿司行きたかった',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0242',
    city: '会津若松',
    word: 'あいつ若ぇのにしにてぇのか',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0243',
    city: '二本松',
    word: '４・３・二本松',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0244',
    city: '相馬',
    word: '獅子馬',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0245',
    city: '福島',
    word: '横縞福島',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0246',
    city: 'いわき',
    word: '磐城城',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0247',
    city: '田村',
    word: '推しな田村',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0248',
    city: '白河',
    word: 'シワカワ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0249',
    city: '郡山',
    word: '強く肯定',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '025',
    city: '新潟',
    word: 'にいごた県',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0250',
    city: '五泉',
    word: '五千',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0252',
    city: '新潟',
    word: '新潟',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0253',
    city: '新潟',
    word: '-',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0254',
    city: '新発田',
    word: '新発田',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0255',
    city: '上越',
    word: 'ここを越えていけ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0256',
    city: '三条',
    word: 'コンロ付き三畳',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0257',
    city: '柏崎',
    word: 'お菓子コーナー',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0258',
    city: '長岡',
    word: '今夜は長いよ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0259',
    city: '佐渡',
    word: '時刻はトキ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '026',
    city: '長野',
    word: 'お風呂が長いの',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0260',
    city: '阿南',
    word: '群れたアナコンダ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0261',
    city: '大町',
    word: 'ロイヤルマッチ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0262',
    city: '長野',
    word: 'お風呂に蛾なの！',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0263',
    city: '松本',
    word: '無惨な松ぼっくり',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0264',
    city: '木曽',
    word: '虫の木そっと',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0265',
    city: '飯田',
    word: 'むごいいだ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0266',
    city: '諏訪',
    word: 'スワローク',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0267',
    city: '小諸',
    word: '胸毛の子供',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0268',
    city: '上田',
    word: '牢屋は上だ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0269',
    city: '飯山',
    word: 'ロックはいいやまだ',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '027',
    city: '群馬',
    word: 'ツナ軍艦',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0270',
    city: '伊勢崎',
    word: '伊勢海老になれー',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0272',
    city: '前橋',
    word: '真夏',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0273',
    city: '高崎',
    word: '高菜さん',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0274',
    city: '富岡',
    word: '製糸場',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0276',
    city: '太田',
    word: '南無お陀仏',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0277',
    city: '桐生',
    word: 'ラッキリューセブン',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0278',
    city: '沼田',
    word: 'ナンパは沼だ',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0279',
    city: '渋川',
    word: '泣く泣く渋柿',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '028',
    city: '栃木',
    word: 'ツヤツヤとちおとめ',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0280',
    city: '古河',
    word: 'あの子がパレード',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0281',
    city: ' 鉾田',
    word: 'パイを誇った',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0282',
    city: '栃木',
    word: 'とちおとめパンツ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0283',
    city: '佐野',
    word: '佐野',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0284',
    city: '足利',
    word: 'パシリの足',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0285',
    city: '小山',
    word: '箱の山',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0286',
    city: '宇都宮',
    word: 'ハロウツノミヤ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0287',
    city: '那須塩原',
    word: '高原バナナ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0288',
    city: '日光',
    word: 'パパもニッコリ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0289',
    city: '鹿沼',
    word: '野球馬鹿の沼',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '029',
    city: '茨城',
    word: '畑のお肉 水戸納豆',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0292',
    city: '水戸',
    word: '水戸光圀',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0293',
    city: '高萩',
    word: '高すぎに草',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0294',
    city: '常陸太田',
    word: 'つくし太く立つ',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0295',
    city: '常陸大宮',
    word: '求婚は大見え切って',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0296',
    city: '笠間',
    word: '黒い傘間に合ってます',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0297',
    city: '坂東',
    word: '苦難のバンド',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0298',
    city: '土浦',
    word: '裏側は吸盤',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0299',
    city: '鹿嶋',
    word: '救急箱貸しますか？',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '03 ',
    city: '東京',
    word: '東京03',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '03xx',
    city: '狛江',
    word: '三コマ漫画',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '042',
    city: '八王子',
    word: '四二が八王子',
    dateAisu: '12/09',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0420',
    city: '所沢',
    word: 'それがつれぇ所沢',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0422',
    city: '武蔵野',
    word: 'にんにん武者修行',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0423',
    city: '国分寺',
    word: '兄さんが国を分ける',
    dateAisu: '12/09',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0424',
    city: '西東京',
    word: '西東京',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0425',
    city: '立川',
    word: '濁ったちいかわ',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0426',
    city: '八王子',
    word: '王子の任務',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0427',
    city: '相模原',
    word: '横綱相撲',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0428',
    city: '青梅',
    word: 'つっぱい梅干し',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0429',
    city: '飯能',
    word: '肉と飯',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '043',
    city: '千葉',
    word: '',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0432',
    city: '千葉',
    word: '札で千羽鶴',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0433',
    city: '千葉',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0434',
    city: '千葉',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0436',
    city: '市原',
    word: '腹だすと寒い',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0438',
    city: '木更津',
    word: '砂漠は更地',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0439',
    city: '君津',
    word: 'キミク',
    dateAisu: '12/09',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '044',
    city: '川崎',
    word: '指定都市川崎',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '044x',
    city: '川崎',
    word: '指定都市川崎',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '045',
    city: '横浜',
    word: 'ヨコ',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '045x',
    city: '横浜',
    word: 'ヨコ',
    dateAisu: '10/20',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '046',
    city: '鎌倉',
    word: '無敵のお城 神奈川県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0460',
    city: '箱根',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0462',
    city: '厚木',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0463',
    city: '平塚',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0464',
    city: '厚木',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0465',
    city: '小田原',
    word: '酷い包囲だ小田原征伐',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0466',
    city: '藤沢',
    word: 'ろくろっふじ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0467',
    city: '鎌倉',
    word: '鎌倉武士の胸騒ぎ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0468',
    city: '横須賀',
    word: '海軍の牢屋',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '047',
    city: '千葉',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0470',
    city: '鴨川',
    word: '鴨になれよ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0471',
    city: '柏',
    word: 'お菓子はないのだなぁ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0473',
    city: '市川',
    word: 'NASA天の川',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0474',
    city: '船橋',
    word: 'ふなっしー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0475',
    city: '茂原',
    word: 'モナコ腹',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0476',
    city: '成田',
    word: 'なろう飛行機',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0477',
    city: '船橋',
    word: 'らっきーせぶんなっしー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0478',
    city: '香取',
    word: '納屋の香り取り',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0479',
    city: '銚子',
    word: '調子に乗るなくそやろう泣くな！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '048',
    city: '埼玉',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0480',
    city: '久喜',
    word: 'パリパリクッキー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0482',
    city: '川口',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0483',
    city: '川口',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0484',
    city: '川口',
    word: '川口詰みよ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0485',
    city: '熊谷',
    word: '子熊',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0486',
    city: 'さいたま',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0487',
    city: 'さいたま',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0488',
    city: 'さいたま',
    word: 'ハローバイバイさいたま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0489',
    city: '草加',
    word: 'はっくしょん草',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '049',
    city: '秩父',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0492',
    city: '川越',
    word: '小国川越',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0493',
    city: '東松山',
    word: '待つしぐさやま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0494',
    city: '秩父',
    word: '櫛通す父',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0495',
    city: '本庄',
    word: '中古本女子',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0499',
    city: '大島',
    word: 'クック大島行き',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '052',
    city: '名古屋',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '052x',
    city: '名古屋',
    word: 'コツコツと真逆名古屋人',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '053',
    city: '浜松',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0531',
    city: '田原',
    word: '田←サイコロ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0532',
    city: '豊橋',
    word: '小作人も富む端っこ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0533',
    city: '豊川',
    word: '小耳にヘップバーン',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0534',
    city: '浜松',
    word: '兵公ご察し',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0535',
    city: '浜松',
    word: '兵公ざぁこ♡',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0536',
    city: '設楽',
    word: 'スベルバナナマン',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0537',
    city: '掛川',
    word: 'みんな掛けそば',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0538',
    city: '磐田',
    word: 'サッカーサンバジュビロ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0539',
    city: '浜松',
    word: '三来だよー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '054',
    city: '静岡',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0542',
    city: '静岡',
    word: '42おか',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0543',
    city: '#VALUE!',
    word: '#VALUE!',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0544',
    city: '富士宮',
    word: '自死不死の都',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0545',
    city: '富士',
    word: '千代の富士四股',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0546',
    city: '静岡',
    word: 'SIM謳歌',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0547',
    city: '島田',
    word: 'シナの島だ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0548',
    city: '牧之原',
    word: 'マキの小ジワ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0549',
    city: '静岡',
    word: 'よく出る静岡',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '055',
    city: '甲府',
    word: 'こここ甲府市',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0550',
    city: '御殿場',
    word: '510場',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0551',
    city: '韮崎',
    word: '551のニラマン',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0552',
    city: '甲府',
    word: '午後に52',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0553',
    city: '山梨',
    word: 'ゴミ山無し',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0554',
    city: '大月',
    word: '今宵の大きい月',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0555',
    city: '富士吉田',
    word: 'よ死ゴーゴーゴー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0556',
    city: '富士川',
    word: '富士は日本の心',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0557',
    city: '熱海',
    word: '暑海ココナッツ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0558',
    city: '下田',
    word: '黒船怖い下田ココア',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0559',
    city: '沼津',
    word: 'コクのある沼っすね',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '056',
    city: '愛知',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0561',
    city: '瀬戸',
    word: 'セト6位',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0562',
    city: '知多',
    word: 'チーターvsむつごろう',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0563',
    city: '西尾',
    word: '小麦砂糖八橋',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0564',
    city: '岡崎',
    word: '先殺しておかんと',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0565',
    city: '豊田',
    word: 'コロコロトヨタ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0566',
    city: '刈谷',
    word: 'メリーハローサタン高浜',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0567',
    city: '津島',
    word: 'コロナになっつしまった',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0568',
    city: '春日井',
    word: 'ハルヒ牢屋行き',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0569',
    city: '半田',
    word: '無垢なパンダ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '057',
    city: '岐阜',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0572',
    city: '多治見',
    word: '72は地味',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0573',
    city: '恵那',
    word: 'エナコナミ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0574',
    city: '可児',
    word: 'やまなししかご',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0575',
    city: '郡上',
    word: '群青の泣く子',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0576',
    city: '下呂',
    word: 'コナロゲロ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0577',
    city: '高山',
    word: '77宝の山',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0578',
    city: '飛騨',
    word: 'オコな矢被弾',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '058',
    city: '一宮',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0581',
    city: '本巣',
    word: '事後パイを戻すし',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0582',
    city: '岐阜',
    word: '小屋に寄付',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0583',
    city: '岐阜',
    word: '寄付後破産',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0584',
    city: '大垣',
    word: '橋の大垣壊しちゃえオオガキ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0585',
    city: '揖斐川',
    word: '奴イビリ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0586',
    city: '一宮',
    word: 'はろーみや',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0587',
    city: '稲沢',
    word: 'バナナ稲作',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '059',
    city: '三重',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0592',
    city: '津',
    word: '苦痛',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0593',
    city: '四日市',
    word: '四日坊主のコックさん',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0594',
    city: '桑名',
    word: 'こ桑名市無双',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0595',
    city: '伊賀',
    word: '忍者の国語',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0596',
    city: '伊勢',
    word: '黒伊勢神宮',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0597',
    city: '尾鷲',
    word: '大雨救難信号',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0598',
    city: '松阪',
    word: '松坂牛クッパ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0599',
    city: '志摩',
    word: '鹿嶋志摩',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '06 ',
    city: '大阪',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '2',
    areacode: '06',
    city: '尼崎',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '072',
    city: '堺',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0721',
    city: '富田林',
    word: '家政婦林はみたなにい！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0722',
    city: '堺',
    word: '世界津々浦々',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0723',
    city: '堺',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0724',
    city: '岸和田',
    word: 'にしわだ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0725',
    city: '和泉',
    word: 'わいずみ！ニコッ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0726',
    city: '茨木',
    word: 'イバラで吊ろう',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0727',
    city: '池田',
    word: 'ツナ缶池田',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0728',
    city: '寝屋川',
    word: '寝ながら通夜',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0729',
    city: '柏原',
    word: '菓子な生肉',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '073',
    city: '和歌山',
    word: '◎なミカンの 和歌山県',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0734',
    city: '和歌山',
    word: '三枝の和歌',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0735',
    city: '新宮',
    word: '竜宮サンゴ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0736',
    city: '橋本',
    word: '橋橋下寒し',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0737',
    city: '有田',
    word: '並な有田みかん',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0738',
    city: '御坊',
    word: 'ごぼうサンバ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0739',
    city: '田辺',
    word: '鴨ねぎなべみく',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '074',
    city: '奈良',
    word: '◎なシカたちの奈良県',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0740',
    city: '高島',
    word: 'たか40たか',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0742',
    city: '奈良',
    word: '鹿にさよなら',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0743',
    city: '生駒',
    word: '駒予算不足でも生駒',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0744',
    city: '桜井',
    word: '夜桜いい',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0745',
    city: '葛城',
    word: '葛シコ富嶽46景',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0746',
    city: '吉野',
    word: '白すぎ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0747',
    city: '五條',
    word: '五条:死なない',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0748',
    city: '近江八幡',
    word: 'シワトリ製薬会社',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0749',
    city: '彦根',
    word: '欲張りひこにゃん',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '075',
    city: '京都',
    word: '女子(おなご)の京都',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '075x',
    city: '京都',
    word: '向こうに長い髪の柔肌少女',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '076',
    city: '石川',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0761',
    city: '小松',
    word: 'ローピンを待つな',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0762',
    city: '金沢',
    word: 'むに金沢山',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0763',
    city: '砺波市',
    word: 'ろなみ十並み',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0764',
    city: '富山',
    word: '虫の山',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0765',
    city: '魚津',
    word: 'サカナムコプロ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0766',
    city: '高岡',
    word: 'ロロ→高 おかしいやろ！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0767',
    city: '七尾',
    word: '七尾七',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0768',
    city: '輪島',
    word: '8ま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '077',
    city: '大津',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0770',
    city: '小浜',
    word: 'オバマハゼロ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0771',
    city: '亀岡',
    word: '亀が無い頭おかしい',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0772',
    city: '宮津',
    word: 'みなつ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0773',
    city: '福知山',
    word: '73チサン知山',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0774',
    city: '宇治',
    word: 'ウ4',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0775',
    city: '大津',
    word: '名古大っ！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0776',
    city: '福井',
    word: 'なむご冥福い',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0778',
    city: '鯖江',
    word: 'はずれサーバーへ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0779',
    city: '大野',
    word: 'なくなオーノー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '078',
    city: '神戸',
    word: '◎なハーバー 神戸港',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '078x',
    city: '神戸',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '079',
    city: '姫路',
    word: '◎なクイーンの姫路城',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0790',
    city: '加西',
    word: '火災保険くれ！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0791',
    city: 'たつの',
    word: '悔いは先にたつの？',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0792',
    city: '姫路',
    word: 'クイーン姫路の国',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0793',
    city: '姫路',
    word: '文化無くさないで',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0794',
    city: '加古川',
    word: '棋士の町加古川',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0795',
    city: '丹波',
    word: 'なくこも丹波',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0795',
    city: '三田',
    word: '要救護サンタ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0796',
    city: '豊岡',
    word: 'なー黒いタピオカなくシックス',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0797',
    city: '宝塚',
    word: '無くなった宝塚',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0798',
    city: '西宮',
    word: 'クッパ城西宮',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0799',
    city: '淡路',
    word: '99は島',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '082',
    city: '広島',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0820',
    city: '柳井',
    word: '柳井でも鰻釣れ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0822',
    city: '広島',
    word: 'パンツにしま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0823',
    city: '呉',
    word: '兄さんをくれ！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0824',
    city: '三次',
    word: 'にじさんじ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0824',
    city: '東広島',
    word: '西に東広島',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0825',
    city: '広島',
    word: '初恋広場',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0826',
    city: '安芸高田',
    word: '積むゲー高校',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0827',
    city: '岩国',
    word: '岩のりツナマヨ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0828',
    city: '広島',
    word: 'パンツはひま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0829',
    city: '廿日市',
    word: '廿日市肉特売でパニック',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '083',
    city: '山口',
    word: '闇で危険な山口県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0832',
    city: '下関',
    word: 'けいサツ関',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0833',
    city: '下松',
    word: 'さんざん嘘松',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0834',
    city: '周南',
    word: '馬刺周知な',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0835',
    city: '防府',
    word: 'ザコを防ぐ抱負',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0836',
    city: '宇部',
    word: '挟む→うげ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0837',
    city: '長門',
    word: 'みんなの長門',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0838',
    city: '萩',
    word: '破産は義',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0839',
    city: '山口',
    word: 'サンクチ山口',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '084',
    city: '福山',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0845',
    city: '尾道',
    word: '横の道シコの道',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0846',
    city: '竹原',
    word: '城ピストル',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0847',
    city: '府中',
    word: '世直し中',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0848',
    city: '三原',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0849',
    city: '福山',
    word: 'よくふくやま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '085',
    city: '鳥取島根',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0851',
    city: '隠岐の島',
    word: '箱入り奥の島',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0852',
    city: '松江',
    word: 'はとこに末裔',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0853',
    city: '出雲',
    word: '古参出雲そば/イズゴミソバ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0854',
    city: '安来',
    word: 'おこしやす',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0855',
    city: '浜田',
    word: 'ゴゴゴリラ浜田',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0856',
    city: '益田',
    word: 'M•D•スフィ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0857',
    city: '鳥取',
    word: '粉っぽい砂丘',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0858',
    city: '倉吉',
    word: 'ゴーヤの倉ヨシ！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0859',
    city: '米子',
    word: 'まいごで号泣',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '086',
    city: '岡山',
    word: 'HELLO! 大都市岡山県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0862',
    city: '岡山',
    word: 'むにからうまれたむにたろう',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0863',
    city: '玉野',
    word: '玉に無残',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0864',
    city: '倉敷',
    word: '64らしきもの',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0865',
    city: '笠岡',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0866',
    city: '高梁',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0867',
    city: '新見',
    word: 'むなしいみ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0868',
    city: '津山',
    word: 'はむはーつ山',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0869',
    city: '備前',
    word: 'ロック装備前',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '087',
    city: '香川',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0875',
    city: '観音寺',
    word: '泣く子に観念寺',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0877',
    city: '丸亀',
    word: '丸亀バナナうどん',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0878',
    city: '高松',
    word: '花は高松',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0879',
    city: 'さぬき',
    word: 'たぬきは泣くぞ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '088',
    city: '徳島高知',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0880',
    city: '四万十',
    word: '晴れて気温が四万十',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0883',
    city: '阿波',
    word: 'ババさん阿波踊り',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0884',
    city: '阿南',
    word: 'はしっこあはん',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0885',
    city: '小松島',
    word: '母は子待つ島',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0886',
    city: '徳島',
    word: '特売ハム',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0887',
    city: '室戸',
    word: '母なる教室',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0888',
    city: '高知',
    word: 'はははは高知',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0889',
    city: '須崎',
    word: 'はやくするさき',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '089',
    city: '愛媛',
    word: '野球拳は愛媛県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0892',
    city: '久万高原町',
    word: 'クズマン高原',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0893',
    city: '大洲',
    word: 'やくざ多すぎ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0894',
    city: '八幡浜',
    word: '白紙に戻せよ八万円',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0895',
    city: '宇和島',
    word: '吐くことうわぁぁ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0896',
    city: '四国中央',
    word: '四黒中央',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0897',
    city: '新居浜',
    word: '新居には来んな',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0898',
    city: '今治',
    word: 'ぱくぱく今治タオル',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0899',
    city: '松山',
    word: '救急車待つやま',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '092',
    city: '福岡',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0920',
    city: '対馬',
    word: 'フレーフレーうま！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '092x',
    city: '福岡',
    word: '福岡のお国',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '093',
    city: '北九州',
    word: 'キタクーサー',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0930',
    city: '行橋',
    word: '去れ！去ってゆくはし',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '093x',
    city: '北九州',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '094',
    city: '久留米',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0940',
    city: '宗像',
    word: 'しゅうぜろ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0942',
    city: '久留米',
    word: '四谷に来るめ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0943',
    city: '八女',
    word: '死産やめて！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0944',
    city: '大牟田',
    word: '牟田口死死',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0946',
    city: '朝倉',
    word: '白い涼子',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0947',
    city: '田川',
    word: 'したがわ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0948',
    city: '飯塚',
    word: 'めしは飯塚',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0949',
    city: '直方',
    word: '四角直方',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '095',
    city: '佐賀長崎',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0950',
    city: '平戸',
    word: '平均50平米',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0952',
    city: '佐賀',
    word: 'こんにさが',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0954',
    city: '武雄',
    word: 'ゴシゴシ洗うよ武雄くん',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0955',
    city: '伊万里',
    word: '伊万←ココ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0956',
    city: '佐世保',
    word: '通信会社ドットコム',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0957',
    city: '島原',
    word: 'コナン灰原粉っぽい',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0958',
    city: '長崎',
    word: 'こんやは長崎で',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0959',
    city: '西海',
    word: '国際会議',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '096',
    city: '熊本',
    word: 'まっくろくまモン 熊本県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0962',
    city: '熊本',
    word: 'むつごろうvs熊',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0963',
    city: '熊本',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0964',
    city: '宇土',
    word: 'うどの虫',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0965',
    city: '八代',
    word: '八代目の婿',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0966',
    city: '水俣',
    word: 'クロム水',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0967',
    city: '阿蘇',
    word: '胸板から阿蘇水',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0968',
    city: '山鹿',
    word: '牢屋は山のようなバカ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0969',
    city: '天草',
    word: '天草四郎百合',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '097',
    city: '大分',
    word: '苦難が多いた 大分県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0972',
    city: '佐伯',
    word: '夏の駅',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0973',
    city: '日田',
    word: 'NASAで宇宙の日だ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0974',
    city: '竹田',
    word: 'ナヨナヨな竹だ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0975',
    city: '大分',
    word: 'だいぶ泣く子',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0977',
    city: '別府',
    word: 'ナナ別府温泉',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0978',
    city: '豊後高田',
    word: 'ナッパごった煮',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0979',
    city: '中津',
    word: 'なくつなかないっ！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '098',
    city: '宮崎',
    word: '奥歯に挟まる宮崎地鶏',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0980',
    city: '名護',
    word: 'パレードの護衛',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0982',
    city: '延岡',
    word: 'パンツ伸ばすよ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0983',
    city: '西都',
    word: '破産のサイト、バッサイト',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0984',
    city: '小林',
    word: 'くばやし',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0985',
    city: '宮崎',
    word: 'ダンボール箱宮殿',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0986',
    city: '都城',
    word: 'ハムの都',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0987',
    city: '日南',
    word: 'にちバナナん。ヒガンバナン',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0988',
    city: '那覇',
    word: 'なははは',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0989',
    city: '那覇',
    word: '#VALUE!',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '099',
    city: '鹿児島',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0991',
    city: '十島',
    word: '9＋1島',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0992',
    city: '鹿児島',
    word: '児童の傀儡馬子にも靴',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0993',
    city: '指宿',
    word: 'いぶくさ',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0994',
    city: '志布志',
    word: 'くしぶし',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0994',
    city: '鹿屋',
    word: 'しかのや',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0995',
    city: '霧島',
    word: '急で濃い霧',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0996',
    city: '出水',
    word: '黒い水が出た！',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0997',
    city: '西之表',
    word: 'うらおもて',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '',
    areacode: '',
    city: '',
    word: '',
    dateAisu: '166',
    dateTorme: '0',
    supplement: '',
  },
]
