export const rememberWordData = [
  {
    length: '3',
    areacode: '011',
    city: '札幌',
    word: 'いい恋人は札幌市',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '※白い恋人：札幌名物のお菓子',
  },
  {
    length: '4',
    areacode: '011x',
    city: '札幌',
    word: 'さっさと別れてきた広島',
    dateAisu: 'きたひろしま"',
    dateTorme: '札幌、厚別、北広島',
    supplement: '10/21',
  },
  {
    length: '3',
    areacode: '012',
    city: '千歳',
    word: 'いつ食べるもの？千歳飴',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0123',
    city: '千歳',
    word: '1・2・3で飛び立て！新千歳空港',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※新千歳空港：北海道の玄関口',
  },
  {
    length: '4',
    areacode: '0124',
    city: '芦別',
    word: 'にしべつあしべつ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0125',
    city: '滝川',
    word: 'ニコニコタッキーカワイイネ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0126',
    city: '岩見沢',
    word: '岩風呂岩見沢',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '013',
    city: '函館',
    word: '函館の遺産は縄文遺跡群',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※垣ノ島遺跡と大船遺跡が登録されている',
  },
  {
    length: '4',
    areacode: '0133',
    city: '石狩',
    word: 'さざれ石借りてくよ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0134',
    city: '小樽',
    word: '刺身の小樽',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※刺身：市場の新鮮な魚介が有名',
  },
  {
    length: '4',
    areacode: '0135',
    city: '余市',
    word: 'いざこざ起こるよ余り1',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0136',
    city: 'ニセコ',
    word: 'さむいニセコのスキー場',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※スキー場：ニセコアンヌプリが有名',
  },
  {
    length: '4',
    areacode: '0137',
    city: '森',
    word: 'みんなの森',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0138',
    city: '函館',
    word: '世界遺産はまだだよ五稜郭',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※「五稜郭と箱館戦争の遺構」で北海道遺産ではある',
  },
  {
    length: '4',
    areacode: '0139',
    city: '松前',
    word: 'サンキューを待つ前に',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '014',
    city: '室蘭',
    word: '美味しい～！室蘭カレーラーメン',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0142',
    city: '伊達',
    word: '異質な伊達者',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0143',
    city: '室蘭',
    word: 'カレーラーメンの美味しさ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※カレーラーメン：室蘭名物のラーメン',
  },
  {
    length: '4',
    areacode: '0144',
    city: '苫小牧',
    word: '獅子舞苫小牧',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※駒大苫小牧のリズムで',
  },
  {
    length: '4',
    areacode: '0145',
    city: '日高',
    word: '横に日高昆布',
    dateAisu: '11/26',
    dateTorme: '',
    supplement: '※日高昆布：煮物にして食べるのによい',
  },
  {
    length: '4',
    areacode: '0146',
    city: '浦河',
    word: '白い襟の裏側は',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '015',
    city: '帯広',
    word: '試されに行こう道東へ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0152',
    city: '網走',
    word: 'ゴツい刑務所網走監獄',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※網走監獄：明治期の刑務所',
  },
  {
    length: '4',
    areacode: '0153',
    city: '根室',
    word: '根菜根室',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※根室は漁業のほうが有名',
  },
  {
    length: '4',
    areacode: '0154',
    city: '釧路',
    word: 'こしろくしろ',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0155',
    city: '帯広',
    word: 'ゴーゴー帯広ばんえい競馬',
    dateAisu: '11/21',
    dateTorme: '',
    supplement: '※ばんえい競馬：馬がそりを引くタイプの競馬',
  },
  {
    length: '4',
    areacode: '0156',
    city: '本別',
    word: 'コロコロコミック別冊',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0157',
    city: '北見',
    word: '小麦の粉は北見産',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '※小麦：菓子用薄力小麦「北見95号」が有名',
  },
  {
    length: '4',
    areacode: '0158',
    city: '紋別',
    word: 'ゴーヤの紋章',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '016',
    city: '旭川',
    word: '以北の果ては道北です',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0162',
    city: '稚内',
    word: '唯一無二もわっかんない',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0163',
    city: '天塩',
    word: '霧散霧塩',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '※霧散霧消',
  },
  {
    length: '4',
    areacode: '0164',
    city: '留萌',
    word: '虫に萌え',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0165',
    city: '名寄',
    word: '別なよろこび',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0166',
    city: '旭川',
    word: 'ろくろ首みたいキリンさん',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※キリンさん：旭山動物園のアミメキリン',
  },
  {
    length: '4',
    areacode: '0167',
    city: '富良野',
    word: 'いろんな種類のラベンダー',
    dateAisu: '11/25',
    dateTorme: '',
    supplement: '※ラベンダー：富良野の名産品',
  },
  {
    length: '3',
    areacode: '017',
    city: '青森',
    word: '青の稲妻 青森県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '※稲妻：「青天の霹靂」が青森のブランド米',
  },
  {
    length: '4',
    areacode: '0172',
    city: '弘前',
    word: '夏前',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※0272：前橋',
  },
  {
    length: '4',
    areacode: '0173',
    city: '五所川原',
    word: '波に乗れ揚げたい焼き',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※揚げたい焼き：五所川原名物',
  },
  {
    length: '4',
    areacode: '0174',
    city: '今別',
    word: '梨と今別れよう',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0175',
    city: 'むつ',
    word: 'なごむつ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※和む',
  },
  {
    length: '4',
    areacode: '0176',
    city: '十和田',
    word: '南無は永遠だ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0177',
    city: '青森',
    word: '旧暦の7月7日はねぶた祭',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※ねぶた祭：東北三大祭りの一つ',
  },
  {
    length: '4',
    areacode: '0178',
    city: '八戸',
    word: '八戸',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0179',
    city: '三戸',
    word: '泣くほどうまいニンニクサンド',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※ニンニク：田子の名産品',
  },
  {
    length: '3',
    areacode: '018',
    city: '秋田',
    word: '18歳の秋田美人',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0182',
    city: '横手',
    word: 'パンツ横縞',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0183',
    city: '湯沢',
    word: '婆さんの湯',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0184',
    city: '由利本荘',
    word: 'いやよユリに過保護',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0185',
    city: '男鹿',
    word: '箱入りナマハゲ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※ナマハゲ：男鹿半島の来訪神',
  },
  {
    length: '4',
    areacode: '0186',
    city: '大館',
    word: 'ハムもおだてりゃ木に登る',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※豚もおだてりゃ木に登る',
  },
  {
    length: '4',
    areacode: '0187',
    city: '仙北',
    word: '戦国の華、大戦',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0188',
    city: '秋田',
    word: 'はっぱの秋だ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '019',
    city: '岩手',
    word: '岩で行くで！',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0191',
    city: '一関',
    word: '一関',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0192',
    city: '大船渡',
    word: '国々を渡る大船',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0193',
    city: '釜石',
    word: '草の釜揚げ',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0194',
    city: '久慈',
    word: '久慈',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0195',
    city: '二戸',
    word: '救護だニトログリセリン',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '※ニトログリセリン：心臓発作に有効な薬',
  },
  {
    length: '4',
    areacode: '0196',
    city: '盛岡',
    word: '黒い盛岡',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0197',
    city: '北上',
    word: '北には行くな',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0198',
    city: '花巻',
    word: 'くっぱまき',
    dateAisu: '11/27',
    dateTorme: '',
    supplement: '※かっぱまき(遠野はかっぱ伝説が有名)',
  },
  {
    length: '3',
    areacode: '022',
    city: '宮城',
    word: '鬼ずんだもちの宮城県',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '※ずんだ：宮城名物',
  },
  {
    length: '4',
    areacode: '0220',
    city: '登米',
    word: '二重に留め具で挟む',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '※迫町：合併前の自治体名',
  },
  {
    length: '4',
    areacode: '0222',
    city: '仙台',
    word: 'ずずずんだ',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0223',
    city: '岩沼',
    word: '兄さん何も言わぬまま',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0224',
    city: '白石',
    word: '白石',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0225',
    city: '石巻',
    word: 'ニコイチの巻',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0226',
    city: '気仙沼',
    word: '風呂の換気扇',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0227',
    city: '仙台',
    word: '通なずんだ',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0228',
    city: '栗原',
    word: 'つやつやの栗だって',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '※築館町：合併前の自治体名',
  },
  {
    length: '4',
    areacode: '0229',
    city: '大崎',
    word: '古い肉の多さ',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '※古川市：合併前の自治体名',
  },
  {
    length: '3',
    areacode: '023',
    city: '山形',
    word: '鬼さくらんぼの山形県',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '※さくらんぼ：山形の名産品',
  },
  {
    length: '4',
    areacode: '0233',
    city: '新庄',
    word: '新庄三球三振',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '※新庄：新庄剛志(元プロ野球選手)',
  },
  {
    length: '4',
    areacode: '0234',
    city: '酒田',
    word: '刺身とお酒',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0235',
    city: '鶴岡',
    word: '亀から見たら 鶴はザコ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '※鶴は千年、亀は万年',
  },
  {
    length: '4',
    areacode: '0236',
    city: '山形',
    word: '兄さん向こうの山が回転',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0237',
    city: '村山',
    word: 'みんなの村',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0238',
    city: '米沢',
    word: '米沢牛を捌く',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '※米沢牛：日本三大和牛',
  },
  {
    length: '3',
    areacode: '024',
    city: '福島',
    word: 'ふーしま県',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0240',
    city: '大熊',
    word: '夜空のおおぐま座',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0241',
    city: '喜多方',
    word: 'お寿司行きたかった',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0242',
    city: '会津若松',
    word: '西に進めばあいつが待つ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0243',
    city: '二本松',
    word: '4・3・二本松',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0244',
    city: '相馬',
    word: 'シシュウマイ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0245',
    city: '福島',
    word: '横縞服の縞',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0246',
    city: 'いわき',
    word: '磐城',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0247',
    city: '田村',
    word: 'シナムラ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '※シマムラ、シナガワ：0947 田川',
  },
  {
    length: '4',
    areacode: '0248',
    city: '白河',
    word: 'シワカワ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0249',
    city: '郡山',
    word: '強く肯定',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '025',
    city: '新潟',
    word: 'にいごた県',
    dateAisu: '11/28',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0250',
    city: '五泉',
    word: '五千',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0252',
    city: '新潟',
    word: '新潟',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0253',
    city: '新潟',
    word: '-',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0254',
    city: '新発田',
    word: '新発田',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0255',
    city: '上越',
    word: 'ここを越えていけ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0256',
    city: '三条',
    word: 'ゴロツキ参上！',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0257',
    city: '柏崎',
    word: 'お菓子コーナー',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0258',
    city: '長岡',
    word: '今夜は長いよ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0259',
    city: '佐渡',
    word: '時刻はトキ',
    dateAisu: '12/03',
    dateTorme: '',
    supplement: '※トキ：佐渡で保護飼育されている',
  },
  {
    length: '3',
    areacode: '026',
    city: '長野',
    word: 'お風呂が長いの 長野県',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0260',
    city: '阿南',
    word: '群れたアナコンダ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0261',
    city: '大町',
    word: 'ロイヤルマッチ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0262',
    city: '長野',
    word: 'お風呂に蛾なの！',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0263',
    city: '松本',
    word: '無惨な松',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0264',
    city: '木曽',
    word: '虫の木そっと',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0265',
    city: '飯田',
    word: 'むごいいだ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0266',
    city: '諏訪',
    word: 'モクモク 諏訪の工業地帯',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '※諏訪工業地帯：時計などの精密機械工業が有名',
  },
  {
    length: '4',
    areacode: '0267',
    city: '小諸',
    word: '胸毛の子供',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0268',
    city: '上田',
    word: '牢屋は上だ',
    dateAisu: '12/05',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0269',
    city: '飯山',
    word: 'ロックマウンテン',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '027',
    city: '群馬',
    word: 'ツナ軍艦の 群馬県',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0270',
    city: '伊勢崎',
    word: '伊勢海老になれー',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0272',
    city: '前橋',
    word: '夏前',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '※0172：弘前',
  },
  {
    length: '4',
    areacode: '0273',
    city: '高崎',
    word: '高菜さん',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0274',
    city: '富岡',
    word: '富岡製糸場',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '※富岡製糸場：明治期の官営工場',
  },
  {
    length: '4',
    areacode: '0276',
    city: '太田',
    word: '南無お陀仏',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0277',
    city: '桐生',
    word: 'ラッキリューセブン',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0278',
    city: '沼田',
    word: '沼で難破',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0279',
    city: '渋川',
    word: '泣く泣く渋柿',
    dateAisu: '12/06',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '028',
    city: '栃木',
    word: 'ツヤツヤとちおとめ',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '※とちおとめ：栃木発のいちごの品種',
  },
  {
    length: '4',
    areacode: '0280',
    city: '古河',
    word: 'あの子がパレード',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0281',
    city: '鉾田',
    word: 'パイを誇った',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0282',
    city: '栃木',
    word: 'とちおとめパンツ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '※いちごパンツ',
  },
  {
    length: '4',
    areacode: '0283',
    city: '佐野',
    word: '佐野',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0284',
    city: '足利',
    word: 'パシリの足',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0285',
    city: '小山',
    word: '箱の山',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0286',
    city: '宇都宮',
    word: 'ハロウツノミヤ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0287',
    city: '那須塩原',
    word: 'バナナナス',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0288',
    city: '日光',
    word: 'パパもニッコリ',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0289',
    city: '鹿沼',
    word: '野球馬鹿の沼',
    dateAisu: '12/07',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '029',
    city: '茨城',
    word: '畑のお肉 水戸納豆',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '※水戸納豆：水戸の名産',
  },
  {
    length: '4',
    areacode: '0292',
    city: '水戸',
    word: '水戸光圀',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '※水戸光圀：水戸黄門',
  },
  {
    length: '4',
    areacode: '0293',
    city: '高萩',
    word: '高すぎに草',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0294',
    city: '常陸太田',
    word: 'つくし、太く立つ',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0295',
    city: '常陸大宮',
    word: '求婚は大見え切って',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0296',
    city: '笠間',
    word: '黒い傘間に合ってます',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0297',
    city: '坂東',
    word: '苦難のバンド',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0298',
    city: '土浦',
    word: 'つくば',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '※ＭＡは土浦市だが「つくば」が綺麗すぎるので',
  },
  {
    length: '4',
    areacode: '0299',
    city: '鹿嶋',
    word: '救急箱貸します',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '03 ',
    city: '東京',
    word: '東京03',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '03xx',
    city: '狛江',
    word: '三コマ漫画',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '042',
    city: '八王子',
    word: '四二が八王子',
    dateAisu: '12/09',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0420',
    city: '所沢',
    word: 'それがつれぇ所沢',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0422',
    city: '武蔵野',
    word: 'にんにん武者修行',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0423',
    city: '国分寺',
    word: '兄さんが国を分ける',
    dateAisu: '12/09',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0424',
    city: '西東京',
    word: '西東京',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0425',
    city: '立川',
    word: '濁ったちいかわ',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0426',
    city: '八王子',
    word: '王子の任務',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0427',
    city: '相模原',
    word: '横綱相撲',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0428',
    city: '青梅',
    word: 'つっぱい梅干し',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0429',
    city: '飯能',
    word: '肉と飯',
    dateAisu: '12/08',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '043',
    city: '千葉',
    word: '',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0432',
    city: '千葉',
    word: '札で千羽鶴',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0433',
    city: '千葉',
    word: '札で千羽鶴',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0434',
    city: '千葉',
    word: '札で千羽鶴',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0436',
    city: '市原',
    word: '寒い１月に腹だすと',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0438',
    city: '木更津',
    word: '砂漠は更地',
    dateAisu: '12/10',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0439',
    city: '君津',
    word: 'キミク',
    dateAisu: '12/09',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '044',
    city: '川崎',
    word: '何CC?カワサキバイク',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '044x',
    city: '川崎',
    word: '何CC?カワサキバイク',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '045',
    city: '横浜',
    word: 'ヨコ',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '045x',
    city: '横浜',
    word: 'ヨコ',
    dateAisu: '10/20',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '046',
    city: '鎌倉',
    word: '無敵のお城 神奈川県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0460',
    city: '箱根',
    word: 'ランナーの群れ 箱根駅伝',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0462',
    city: '厚木',
    word: 'むずむず暑い/蒸し暑い',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0463',
    city: '平塚',
    word: 'むさ苦しい平屋',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0464',
    city: '厚木',
    word: 'むずむず暑い/蒸し暑い',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0465',
    city: '小田原',
    word: 'ムゴイ包囲だ小田原征伐',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0466',
    city: '藤沢',
    word: 'ろくろっふじ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0467',
    city: '鎌倉',
    word: 'いい胸毛だね鎌倉武士',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0468',
    city: '横須賀',
    word: '海軍の牢屋',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '047',
    city: '千葉',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0470',
    city: '鴨川',
    word: '鴨になれよ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0471',
    city: '柏',
    word: 'お菓子はないのだなぁ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: 'のだなぁは野田流山我孫子',
  },
  {
    length: '4',
    areacode: '0473',
    city: '市川',
    word: 'NASAの天の川',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0474',
    city: '船橋',
    word: 'ふなっしー',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0475',
    city: '茂原',
    word: 'モナコ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0476',
    city: '成田',
    word: 'なろた空港',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0477',
    city: '船橋',
    word: 'らっきーせぶんなっしー',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0478',
    city: '香取',
    word: '納屋の蚊取り線香',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0479',
    city: '銚子',
    word: '調子悪くても泣くな',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '048',
    city: '埼玉',
    word: 'やさいたま',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0480',
    city: '久喜',
    word: 'バレーボールの空気入れ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0482',
    city: '川口',
    word: 'パッツンカワイイ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0483',
    city: '川口',
    word: 'パッツンカワイイ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0484',
    city: '川口',
    word: 'パッツンカワイイ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0485',
    city: '熊谷',
    word: '子熊',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0486',
    city: 'さいたま',
    word: 'ハムを裂いたま',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0487',
    city: 'さいたま',
    word: 'ハムを裂いたま',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0488',
    city: 'さいたま',
    word: 'ハムを裂いたま',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0489',
    city: '草加',
    word: 'パクパク草加せんべい',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '049',
    city: '秩父',
    word: 'くさいたま',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0492',
    city: '川越',
    word: '武蔵の国 川越',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0493',
    city: '東松山',
    word: '草を待つヤマアラシ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: 'アラシは嵐山',
  },
  {
    length: '4',
    areacode: '0494',
    city: '秩父',
    word: '櫛で梳かす父',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0495',
    city: '本庄',
    word: '中古本女子',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0499',
    city: '大島',
    word: 'クック諸島',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '052',
    city: '名古屋',
    word: 'ゴツイ個性の名古屋めし',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '052x',
    city: '名古屋',
    word: 'ゴツイ個性の名古屋めし',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '053',
    city: '浜松',
    word: '出世大名 家康でござる',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0531',
    city: '田原',
    word: '咲いた原',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0532',
    city: '豊橋',
    word: '考察の端くれ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0533',
    city: '豊川',
    word: 'サラサラ流れる豊かな川',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0534',
    city: '浜松',
    word: 'うなぎの刺身',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0535',
    city: '浜松',
    word: 'うなぎの刺身',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0536',
    city: '新城',
    word: '寒い新雪',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '雪は設楽',
  },
  {
    length: '4',
    areacode: '0537',
    city: '掛川',
    word: 'みんなの架け橋',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0538',
    city: '磐田',
    word: 'サンバで祝った',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0539',
    city: '浜松',
    word: '浜松生まれの初音ミク',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '054',
    city: '静岡',
    word: '4ずおか',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0542',
    city: '静岡',
    word: '42おか',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0543',
    city: '静岡',
    word: '42おか',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0544',
    city: '富士宮',
    word: 'よきよき！ 富士宮焼きそば',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0545',
    city: '富士',
    word: '富士の四股',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0546',
    city: '静岡',
    word: '46おか',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0547',
    city: '島田',
    word: 'シナダ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0548',
    city: '牧之原',
    word: 'マキちゃんの小ジワ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0549',
    city: '静岡',
    word: 'よく出る静岡',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '055',
    city: '甲府',
    word: 'こここ甲府',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0550',
    city: '御殿場',
    word: 'ゴテン場',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0551',
    city: '韮崎',
    word: 'ココイチ ニラカレー',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0552',
    city: '甲府',
    word: '52(こーふ)',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0553',
    city: '山梨',
    word: 'ごみの山無し',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0554',
    city: '大月',
    word: '今宵の大きい月',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0555',
    city: '富士吉田',
    word: 'ゴーゴーゴー！ 富士急ハイランド',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0556',
    city: '富士川',
    word: '日本の心 富士と川',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0557',
    city: '熱海',
    word: 'ココナッツは熱い海で',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0558',
    city: '下田',
    word: '霜だ！ココア飲も',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0559',
    city: '沼津',
    word: 'まずい！ゴクゴク',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '056',
    city: '愛知',
    word: 'コロコロトヨタ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0561',
    city: '瀬戸',
    word: '瀬戸際公務員',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0562',
    city: '知多',
    word: 'むつごろうVSチーター',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0563',
    city: '西尾',
    word: '無味に塩',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0564',
    city: '岡崎',
    word: '蒸しておかなきゃ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0565',
    city: '豊田',
    word: 'コロコロトヨタ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0566',
    city: '刈谷',
    word: 'ろくろを借りた',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0567',
    city: '津島',
    word: 'コロナになっつしまった',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0568',
    city: '春日井',
    word: 'ロバを貸すが',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0569',
    city: '半田',
    word: '無垢なパンダ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '057',
    city: '岐阜',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0572',
    city: '多治見',
    word: '夏は地味',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0573',
    city: '恵那',
    word: 'ええなぁ(小並感)',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0574',
    city: '可児',
    word: 'やまなしの蟹',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0575',
    city: '郡上',
    word: '七五調で描く群青',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0576',
    city: '下呂',
    word: 'ゲロゲロになろう！',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0577',
    city: '高山',
    word: 'ラッキーセブンで宝の山',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0578',
    city: '飛騨',
    word: '納屋に被弾',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '058',
    city: '一宮',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0581',
    city: '本巣',
    word: '牌を戻すし',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0582',
    city: '岐阜',
    word: 'パンツを寄付',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0583',
    city: '岐阜',
    word: 'パンツを寄付',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0584',
    city: '大垣',
    word: '走るガキ大将',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0585',
    city: '揖斐川',
    word: '箱いび娘',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0586',
    city: '一宮',
    word: 'はろーみや',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0587',
    city: '稲沢',
    word: 'バナナ稲作',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '059',
    city: '三重',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0592',
    city: '津',
    word: '苦痛',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0593',
    city: '四日市',
    word: '四日坊主のコックさん',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0594',
    city: '桑名',
    word: '国わな士無双',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '※国士無双',
  },
  {
    length: '4',
    areacode: '0595',
    city: '亀山',
    word: '亀さんの国語',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0596',
    city: '伊勢',
    word: '黒い伊勢海老',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0597',
    city: '尾鷲',
    word: '大雨救難信号',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0598',
    city: '松阪',
    word: '松坂牛クッパ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0599',
    city: '鳥羽',
    word: 'キュンキュンする言葉',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '06 ',
    city: '大阪',
    word: 'オムそば',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '2',
    areacode: '06',
    city: '尼崎',
    word: '甘いオムレット',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '072',
    city: '堺',
    word: '夏色 坂を下っていく',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0721',
    city: '富田林',
    word: 'なにい！？林が飛んだ！？',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0722',
    city: '堺',
    word: '夏に坂を下っていく',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0723',
    city: '堺',
    word: '夏に坂を下っていく',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0724',
    city: '岸和田',
    word: 'にしわだ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0725',
    city: '和泉',
    word: 'ニコニコはワイのおかげ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0726',
    city: '茨木',
    word: '通路は茨の道',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0727',
    city: '池田',
    word: 'ツナの池だ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0728',
    city: '寝屋川',
    word: 'ニヤガワ',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0729',
    city: '八尾',
    word: '肉屋と八百屋',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '073',
    city: '和歌山',
    word: 'ミカンの 和歌山',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0734',
    city: '和歌山',
    word: '民謡と和歌',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0735',
    city: '新宮',
    word: 'サンゴの竜宮',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0736',
    city: '橋本',
    word: '寒い足元',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0737',
    city: '有田',
    word: '並々ならぬ有田みかん',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0738',
    city: '御坊',
    word: '鯖のごぼう煮',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0739',
    city: '田辺',
    word: 'ざく切り鍋',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '074',
    city: '奈良',
    word: 'シカたちの 奈良公園',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0740',
    city: '高島',
    word: 'たか四万',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0742',
    city: '奈良',
    word: '奈良漬け',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0743',
    city: '生駒',
    word: '予算困った',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0744',
    city: '桜井',
    word: '夜桜',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0745',
    city: '大和高田',
    word: '仕事だからね',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0746',
    city: '吉野',
    word: '素人はよしな',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0747',
    city: '五條',
    word: 'ナヨナヨな御嬢',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0748',
    city: '近江八幡',
    word: '八幡',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0749',
    city: '彦根',
    word: '欲張りひこにゃん',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '075',
    city: '京都',
    word: '女子(おなご)の京都',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '075x',
    city: '京都',
    word: '向こうに長髪柔肌少女',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '076',
    city: '石川',
    word: 'なろうよ金持ち大富豪',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0761',
    city: '小松',
    word: '剥いた小松菜',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0762',
    city: '金沢',
    word: 'ローズゴールド',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0763',
    city: '砺波',
    word: '√3 : 人並みに',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0764',
    city: '富山',
    word: '虫の山',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0765',
    city: '魚津',
    word: 'サカナムコ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0766',
    city: '高岡',
    word: 'ろくろを買おうか',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0767',
    city: '七尾',
    word: '七尾',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0768',
    city: '輪島',
    word: 'ハチマワジマ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '077',
    city: '大津',
    word: 'なんなん！？この割り振られ方',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0770',
    city: '小浜',
    word: '馴れ馴れしいオバマ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0771',
    city: '亀岡',
    word: '噛めない',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0772',
    city: '宮津',
    word: '夏やずみ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0773',
    city: '福知山',
    word: '涙を拭く知山',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0774',
    city: '宇治',
    word: 'ウ4',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0775',
    city: '大津',
    word: 'ナナコで買おうっ！',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0776',
    city: '福井',
    word: '南無で冥福祈ります',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0778',
    city: '鯖江',
    word: '名ばかりのサーバー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0779',
    city: '大野',
    word: '泣く泣くOh NO!',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '078',
    city: '神戸',
    word: 'ハーバーの神戸港',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '078x',
    city: '神戸',
    word: 'ハーバーの神戸港',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '079',
    city: '姫路',
    word: 'クイーンの姫路城',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0790',
    city: '加西',
    word: '火災保険くれ！',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0791',
    city: 'たつの',
    word: 'クイズの達人',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0792',
    city: '姫路',
    word: 'クイーンの国 姫路',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0793',
    city: '姫路',
    word: 'クイーンの国 姫路',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0794',
    city: '加古川',
    word: '棋士の町 加古川',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0795',
    city: '三田',
    word: '泣く子にサンダー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0796',
    city: '豊岡',
    word: '黒いタピオカ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0797',
    city: '宝塚',
    word: '泣くな 宝塚歌劇団',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0798',
    city: '西宮',
    word: 'キューバは西が嫌',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0799',
    city: '淡路',
    word: '救急車 間にあわじ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '082',
    city: '広島',
    word: 'おやつは広島もみじ饅頭',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0820',
    city: '柳井',
    word: 'ノーパンやないかい！',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0822',
    city: '広島',
    word: 'ニコニコヒーロー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0823',
    city: '呉',
    word: '兄さんをくれ！',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0824',
    city: '三次',
    word: 'にじさんじ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0824',
    city: '東広島',
    word: '西に東広島',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0825',
    city: '広島',
    word: 'ニッコリヒーロー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0826',
    city: '安芸高田',
    word: '風呂は飽きた',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0827',
    city: '岩国',
    word: 'ツナマヨ岩のり',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0828',
    city: '広島',
    word: 'ニヤニヤヒーロー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0829',
    city: '廿日市',
    word: '肉が甘くない',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '083',
    city: '山口',
    word: '闇で危険な山口県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0832',
    city: '下関',
    word: '警察の関所',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0833',
    city: '下松',
    word: '散々くだらない話をされる',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0834',
    city: '周南',
    word: 'ばさしゅーなん',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0835',
    city: '防府',
    word: 'ザコを防ぐ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0836',
    city: '宇部',
    word: '挟む→うげ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0837',
    city: '長門',
    word: '7がと',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0838',
    city: '萩',
    word: '8ぎ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0839',
    city: '山口',
    word: 'やみぐち',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '084',
    city: '福山',
    word: '端の福山',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0845',
    city: '尾道',
    word: '横道で',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0846',
    city: '竹原',
    word: '城に竹槍',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0847',
    city: '府中',
    word: '世直し中',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0848',
    city: '三原',
    word: '視野に見晴らし',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0849',
    city: '福山',
    word: 'よき風吹く山',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '085',
    city: '鳥取島根',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0851',
    city: '隠岐の島',
    word: '箱入り隠し子',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0852',
    city: '松江',
    word: '箱庭で松江',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0853',
    city: '出雲',
    word: '古参は出雲そば',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0854',
    city: '安来',
    word: 'やすりでゴシゴシ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0855',
    city: '浜田',
    word: 'ゴリラ浜田',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0856',
    city: '益田',
    word: '航路を決めてマストを立てろ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0857',
    city: '鳥取',
    word: 'コナコナ砂丘',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0858',
    city: '倉吉',
    word: '今夜は暗いね',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0859',
    city: '米子',
    word: '号泣の迷子',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '086',
    city: '岡山',
    word: 'HELLO! 大都市岡山県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0862',
    city: '岡山',
    word: '浪人ももたろう',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0863',
    city: '玉野',
    word: '無産階級玉の輿',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0864',
    city: '倉敷',
    word: '羽虫らしきもの',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0865',
    city: '笠岡',
    word: '婿に傘を貸す',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0866',
    city: '高梁',
    word: 'ろくろが高い',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0867',
    city: '新見',
    word: 'むなしいみ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0868',
    city: '津山',
    word: '老婆つやつや',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0869',
    city: '備前',
    word: 'ロックに備えよ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '087',
    city: '香川',
    word: '花の香り',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0875',
    city: '観音寺',
    word: 'ハナコ観念しろ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0877',
    city: '丸亀',
    word: '丸亀バナナ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0878',
    city: '高松',
    word: '納屋はあったかまつ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0879',
    city: 'さぬき',
    word: '泣くほどうまい讃岐うどん',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '088',
    city: '徳島高知',
    word: 'コーチに拍手を送っとく',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0880',
    city: '四万十',
    word: '8万',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0883',
    city: '阿波',
    word: '婆さんの阿波踊り',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0884',
    city: '阿南',
    word: '端の抜け穴か',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0885',
    city: '小松島',
    word: '小松島',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0886',
    city: '徳島',
    word: '特売ハム',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0887',
    city: '安芸',
    word: '花の香りに飽きた婿',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '※香りは香南・香美　婿は室戸',
  },
  {
    length: '4',
    areacode: '0888',
    city: '高知',
    word: 'コーチに拍手',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0889',
    city: '須崎',
    word: 'はやくするさき',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '089',
    city: '愛媛',
    word: '野球拳は愛媛県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0892',
    city: '久万高原',
    word: '発掘したの久しぶり',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0893',
    city: '大洲',
    word: 'やくざ多すぎ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0894',
    city: '八幡浜',
    word: '白紙に戻せよ八万円',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0895',
    city: '宇和島',
    word: '愚行だうわぁ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0896',
    city: '四国中央',
    word: '四黒中央',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0897',
    city: '新居浜',
    word: '来んな新居に',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0898',
    city: '今治',
    word: '配っていたよ今治タオル',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0899',
    city: '松山',
    word: '救急車待つやま',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '092',
    city: '福岡',
    word: 'お国の始まり 福岡県',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0920',
    city: '対馬',
    word: 'フレーフレー対抗馬！',
    dateAisu: '12/15',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '092x',
    city: '福岡',
    word: 'お国の始まり 福岡県',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '093',
    city: '北九州',
    word: 'キタクーサー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0930',
    city: '行橋',
    word: '去れ！去ってゆくはし',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '093x',
    city: '北九州',
    word: 'キタクーサー',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '094',
    city: '久留米',
    word: '給仕はグルメ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0940',
    city: '宗像',
    word: '指令はなかった',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0942',
    city: '久留米',
    word: '質問が来るね',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0943',
    city: '八女',
    word: '嫁さん八女さん',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0944',
    city: '大牟田',
    word: 'シーシー！無駄口',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0946',
    city: '朝倉',
    word: '白い朝',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0947',
    city: '田川',
    word: 'シナガワタガワ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '※シナムラ：0247 田村',
  },
  {
    length: '4',
    areacode: '0948',
    city: '飯塚',
    word: 'しあわせの飯図鑑',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0949',
    city: '直方',
    word: '四角は長方形',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '095',
    city: '佐賀長崎',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0950',
    city: '平戸',
    word: 'ゴールは平屋一戸建て',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0952',
    city: '佐賀',
    word: '鉱夫の性',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0954',
    city: '武雄',
    word: 'ゴシゴシするだけお',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0955',
    city: '伊万里',
    word: 'こまりいまり',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0956',
    city: '佐世保',
    word: '通信販売会社ドットコム',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0957',
    city: '島原',
    word: '粉骨砕身 島原の乱',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0958',
    city: '長崎',
    word: 'こんやは長崎で',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0959',
    city: '西海',
    word: '国際会議',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '096',
    city: '熊本',
    word: 'まっくろくまモン 熊本県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0962',
    city: '熊本',
    word: 'むつごろうvs熊',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0963',
    city: '熊本',
    word: 'むつごろうvs熊',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0964',
    city: '宇土',
    word: '蒸しうどん',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0965',
    city: '八代',
    word: '婿は八代目',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0966',
    city: '水俣',
    word: 'クロム水',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0967',
    city: '阿蘇',
    word: 'ムナーソ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0968',
    city: '山鹿',
    word: 'クローバー食べるシカ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0969',
    city: '天草',
    word: 'アマクロックサ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '097',
    city: '大分',
    word: '苦難が多いた 大分県',
    dateAisu: '10/21',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0972',
    city: '佐伯',
    word: '夏の駅',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0973',
    city: '日田',
    word: '額の涙',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0974',
    city: '竹田',
    word: 'ナヨナヨな竹だ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0975',
    city: '大分',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0977',
    city: '別府',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0978',
    city: '豊後高田',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0979',
    city: '中津',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '098',
    city: '宮崎',
    word: '奥歯に挟まる宮崎地鶏',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0980',
    city: '名護',
    word: 'パレードの護衛',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0982',
    city: '延岡',
    word: 'パンツ伸ばすよ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0983',
    city: '西都',
    word: '破砕とは',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0984',
    city: '小林',
    word: 'こば84',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0985',
    city: '宮崎',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0986',
    city: '都城',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0987',
    city: '日南',
    word: 'にちなんバナナン',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0988',
    city: '那覇',
    word: 'なははは',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0989',
    city: '那覇',
    word: 'なははは',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '3',
    areacode: '099',
    city: '鹿児島',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0991',
    city: '十島',
    word: 'クイズ十段',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0992',
    city: '鹿児島',
    word: '稚児の靴',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0993',
    city: '指宿',
    word: 'いぶくさ',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0994',
    city: '志布志',
    word: '志布志',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0994',
    city: '鹿屋',
    word: 'しかのや',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0995',
    city: '霧島',
    word: '濃い霧島',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0996',
    city: '出水',
    word: '黒い水が出た！',
    dateAisu: '12/16',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '4',
    areacode: '0997',
    city: '西之表',
    word: '',
    dateAisu: '',
    dateTorme: '',
    supplement: '',
  },
  {
    length: '',
    areacode: '',
    city: '',
    word: '',
    dateAisu: '442',
    dateTorme: '0',
    supplement: '',
  },
]
