export declare const articleContent: string
export declare const articleDate: string
export declare const articleListItem: string
export declare const articleListItemCategory: string
export declare const articleListItemContent: string
export declare const articleListItemDate: string
export declare const articleListItemImg: string
export declare const articleListItemLeft: string
export declare const articleListItemLink: string
export declare const articleListItemRight: string
export declare const articleListItemTitle: string
export declare const articleTitle: string
export declare const blogContent: string
export declare const blogContentArticleInner: string
export declare const blogContentInner: string
export declare const blogContentList: string
export declare const blogNameContainer: string
export declare const blogTopContainer: string
export declare const breadcrumb: string
export declare const mysiteBody: string
