export declare const bgappear: string
export declare const bgappearTrigger: string
export declare const bgextend: string
export declare const bgextendAnimeBase: string
export declare const bgextendAnimeSecond: string
export declare const bgLRextend: string
export declare const bgLRextendAnime: string
export declare const centerBox: string
export declare const dotContent: string
export declare const dotContentContent: string
export declare const dotContentEmuContentOuter: string
export declare const dotContentInner: string
export declare const dotContentSasameContentOuter: string
export declare const emuContent: string
export declare const emuName: string
export declare const footer: string
export declare const footerContainer: string
export declare const gallery: string
export declare const galleryContainer: string
export declare const headline: string
export declare const headlineGreen: string
export declare const headlineMain: string
export declare const headlineSub: string
export declare const imgContainer: string
export declare const imgModal: string
export declare const imgModalThumbContainer: string
export declare const instagram: string
export declare const instagramIframe: string
export declare const introPhoto: string
export declare const introPhotoInner: string
export declare const introProfile: string
export declare const linkButton: string
export declare const linkButtonContainer: string
export declare const linkIcon: string
export declare const linkText: string
export declare const linkTextMain: string
export declare const linkTextSub: string
export declare const mysiteBody: string
export declare const profileContent: string
export declare const profileNameSmall: string
export declare const profileTable: string
export declare const profileText: string
export declare const sasameContent: string
export declare const sasameName: string
export declare const slideIn: string
export declare const slideInInner: string
export declare const socialMediaAuthor: string
export declare const socialMediaButton: string
export declare const socialMediaContent: string
export declare const socialMediaContentContainer: string
export declare const socialMediaFooter: string
export declare const socialMediaHeader: string
export declare const socialMediaHeaderMain: string
export declare const socialMediaHeaderSub: string
export declare const socialMediaIconContainer: string
export declare const socialMediaMain: string
export declare const socialMediaMainColumn: string
export declare const socialMediaMainHeader: string
export declare const socialMediaTitle: string
export declare const tableContainer: string
export declare const tipsBar: string
export declare const tipsContent: string
export declare const topBox: string
export declare const topContent: string
export declare const topImg: string
export declare const topImgBackRect: string
export declare const topImgContainer: string
export declare const topLeftContent: string
export declare const topName: string
export declare const topNameBlue: string
export declare const tormeContent: string
export declare const xtwitter: string
export declare const youtube: string
export declare const youtubeIframe: string
